name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: arc-runner-set

        env:
          DOCKER_HOST: tcp://localhost:2375  # Esto conecta al daemon DinD

        steps:
            - name: Checkout app code
              uses: actions/checkout@v3
      
            - name: Build Docker image
              run: |
                export TAG=$(date +%s)
                echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
                docker build -t asierzd/devops-platform-testapp:$TAG .
            
            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
            - name: Push Docker image
              run: docker push asierzd/devops-platform-testapp:${{ env.IMAGE_TAG }}
      
            - name: Clone GitOps repo
              uses: actions/checkout@v3
              with:
                repository: asierzd/devops-platform-gitops
                path: devops-platform-gitops
                token: ${{ secrets.GITOPS_TOKEN }}
      
            - name: Update image tag in values.yaml
              run: |
                sed -i "s/tag: .*/tag: \"${{ env.IMAGE_TAG }}\"/" devops-platform-gitops/values.yaml
      
            - name: Commit and push changes to GitOps repo
              run: |
                cd devops-platform-gitops
                git config user.name "github-actions"
                git config user.email "actions@github.com"
                git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
                git push origin master
